/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCarouselRouteImport } from './routes/admin.carousel'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarouselRoute = AdminCarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blog'
    | '/admin/carousel'
    | '/admin/fleet'
    | '/admin/services'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/blog'
    | '/admin/carousel'
    | '/admin/fleet'
    | '/admin/services'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/blog'
    | '/admin/carousel'
    | '/admin/fleet'
    | '/admin/services'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carousel': {
      id: '/admin/carousel'
      path: '/carousel'
      fullPath: '/admin/carousel'
      preLoaderRoute: typeof AdminCarouselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCarouselRoute: typeof AdminCarouselRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCarouselRoute: AdminCarouselRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
